-- ============================================================================
-- Catálogo ampliado de monedas
--
-- Pasa de 4 a 20 meme coins. Se vuelve a insertar el catálogo completo con
-- `on conflict do update`, así que es idempotente: ejecutarla dos veces o
-- después de 0001 deja el mismo resultado.
--
-- Debe coincidir con src/lib/coins.ts. Tras cambiar cualquiera de los dos,
-- ejecuta `npm run coins:verify` para confirmar que los ids existen en la API
-- de precios: un id equivocado no da error, la moneda simplemente aparece
-- vacía para siempre.
-- ============================================================================

insert into public.coins (id, slug, symbol, name, accent, accent_ink, tagline, blurb, sort_order)
values
  ('dogecoin', 'dogecoin', 'DOGE', 'Dogecoin', '#F5C542', '#926C04',
   'El abuelo del meme',
   'Nacida en 2013 como una parodia de Bitcoin, Dogecoin acabó siendo la meme coin más longeva y reconocible del mercado.',
   1),
  ('shiba-inu', 'shiba-inu', 'SHIB', 'Shiba Inu', '#FF7A18', '#BE5000',
   'El asesino de Doge',
   'Token ERC-20 lanzado en 2020 con un ecosistema propio (ShibaSwap, Shibarium) construido por una comunidad enorme.',
   2),
  ('pepe', 'pepe', 'PEPE', 'Pepe', '#4ADE80', '#15843E',
   'Meme puro, sin utilidad',
   'Lanzada en 2023 sin impuestos ni roadmap y presumiendo de ello: la tesis es el meme y nada más.',
   3),
  ('bonk', 'bonk', 'BONK', 'Bonk', '#FFB627', '#9C6700',
   'El perro de Solana',
   'La meme coin que reactivó Solana tras el colapso de FTX, repartida por airdrop a la comunidad del ecosistema.',
   4),
  ('dogwifcoin', 'dogwifcoin', 'WIF', 'dogwifhat', '#F77FD0', '#D70894',
   'Un perro con gorro',
   'Un shiba con un gorro de lana rosa. Nació en Solana a finales de 2023 y demostró que no hace falta nada más que una buena imagen.',
   5),
  ('floki', 'floki', 'FLOKI', 'Floki', '#F2601C', '#CA4507',
   'El vikingo',
   'Bautizada por el perro de Elon Musk, es de las pocas meme coins que ha construido producto propio alrededor del token.',
   6),
  ('based-brett', 'based-brett', 'BRETT', 'Brett', '#3B6BF5', '#3165FA',
   'El colega de Pepe',
   'Personaje del mismo cómic que Pepe, convertido en la meme coin insignia de la red Base en 2024.',
   7),
  ('popcat', 'popcat', 'POPCAT', 'Popcat', '#A77BF3', '#884BF3',
   'Pop, pop, pop',
   'El gato que abre la boca, uno de los memes más clicados de internet, convertido en token de Solana.',
   8),
  ('mog-coin', 'mog-coin', 'MOG', 'Mog Coin', '#E94BD6', '#CE14B8',
   'Estética vaporwave',
   'Meme coin de Ethereum construida alrededor de la cultura del ''mogging'' y una estética retro muy reconocible.',
   9),
  ('book-of-meme', 'book-of-meme', 'BOME', 'Book of Meme', '#9E4B3C', '#A0493A',
   'El archivo del meme',
   'Lanzada en Solana en marzo de 2024, fue de las más rápidas de la historia en alcanzar los mil millones de capitalización.',
   10),
  ('baby-doge-coin', 'baby-doge-coin', 'BABYDOGE', 'Baby Doge Coin', '#58B7F0', '#0C77B7',
   'El cachorro',
   'Derivada de la comunidad de Dogecoin en 2021, destaca por tener una de las bases de holders más grandes del sector.',
   11),
  ('spx6900', 'spx6900', 'SPX', 'SPX6900', '#9DC42B', '#627B18',
   'Deja de operar, cree',
   'Parodia del índice S&P 500 cuya única propuesta es superarlo. El chiste es la tesis de inversión.',
   12),
  ('fartcoin', 'fartcoin', 'FARTCOIN', 'Fartcoin', '#E8C93A', '#87710C',
   'Sin comentarios',
   'Surgida a finales de 2024 del ecosistema de agentes de IA en Solana. El nombre lo dice todo.',
   13),
  ('peanut-the-squirrel', 'peanut-the-squirrel', 'PNUT', 'Peanut the Squirrel', '#C97B3C', '#A5612A',
   'En memoria de Peanut',
   'Nacida en noviembre de 2024 como homenaje a Peanut, la ardilla mascota sacrificada por las autoridades de Nueva York.',
   14),
  ('goatseus-maximus', 'goatseus-maximus', 'GOAT', 'Goatseus Maximus', '#24C4A0', '#147F67',
   'La moneda del bot',
   'La primera meme coin impulsada por un agente de inteligencia artificial, Truth Terminal, en octubre de 2024.',
   15),
  ('cat-in-a-dogs-world', 'cat-in-a-dogs-world', 'MEW', 'cat in a dogs world', '#C36BF5', '#AC2AF6',
   'Un gato entre perros',
   'Su tesis está en el nombre: casi todas las meme coins grandes son perros, así que aquí va un gato.',
   16),
  ('pudgy-penguins', 'pudgy-penguins', 'PENGU', 'Pudgy Penguins', '#3FC5E0', '#147C91',
   'Los pingüinos',
   'Token de la colección de NFTs Pudgy Penguins, una de las pocas marcas cripto que ha llegado al mundo físico.',
   17),
  ('notcoin', 'notcoin', 'NOT', 'Notcoin', '#2E9BE6', '#1277BD',
   'De tocar la pantalla',
   'Nació como un juego de clics dentro de Telegram y arrastró a millones de personas a la red TON en 2024.',
   18),
  ('turbo', 'turbo', 'TURBO', 'Turbo', '#7C6BF5', '#6C59F8',
   'Diseñada por una IA',
   'El experimento de crear una meme coin siguiendo las instrucciones de un modelo de lenguaje. Funcionó.',
   19),
  ('apu-apustaja', 'apu-apustaja', 'APU', 'Apu Apustaja', '#7CB342', '#557D2B',
   'El amigo de Pepe',
   'Otra rana del mismo universo de cómics que Pepe, con su propia comunidad en Ethereum.',
   20)
on conflict (id) do update set
  slug       = excluded.slug,
  symbol     = excluded.symbol,
  name       = excluded.name,
  accent     = excluded.accent,
  accent_ink = excluded.accent_ink,
  tagline    = excluded.tagline,
  blurb      = excluded.blurb,
  sort_order = excluded.sort_order;
